# Generated by Django 5.0.6 on 2024-06-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_interval", models.CharField(max_length=10)),
                ("indicator", models.CharField(max_length=10)),
            ],
        ),
    ]
